version: 2
updates:
  - package-ecosystem: bundler
    directory: '/'
    schedule:
      interval: daily
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
  - package-ecosystem: docker
    directory: '/deploy'
    schedule:
      interval: daily
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: daily
  - package-ecosystem: devcontainers
    directory: '/'
    schedule:
      interval: weekly
