source 'https://rubygems.org'

gem 'autoprefixer-rails'
gem 'best_in_place', github: 'luckie/best_in_place', branch: 'multi-select'
gem 'bootstrap-sass', '~> 3.2.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'exifr'
gem 'haml'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'jquery-turbolinks'
gem 'kaminari'
gem 'local_time'
gem 'momentjs-rails'
gem 'paperclip'
gem 'rack-protection'
gem 'rails', '~> 4.2.0'
gem 'rails_config'
gem 'responders', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'secure_headers'
gem 'spring', group: :development
gem 'sqlite3'
gem 'therubyracer', platforms: :ruby
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'
gem 'uuidtools'
