version: '3.2'

services:
  db:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWD}'
    volumes:
      - db:/var/lib/mysql
    restart: always

  redis:
    image: redis:alpine
    volumes:
      - redis:/data
    restart: always

  web: &rails
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
    depends_on:
      - db
      - redis
    volumes:
      - ../config:/app/config
      - storage:/app/storage
    ports:
      - 3000:3000
    environment:
      DATABASE_URL: mysql2://root:$MYSQL_ROOT_PASSWD@db:3306/imgshr?encoding=utf8&pool=5&timeout=5000
      REDIS_PROVIDER: REDIS_URL
      REDIS_URL: redis://redis:6379
      RAILS_ENV: production
      RAILS_FORCE_SSL: 'false'
      RAILS_SERVE_STATIC_FILES: 'true'
      SECRET_KEY_BASE: $SECRET_KEY_BASE
      GITHUB_KEY: $GITHUB_KEY
      GITHUB_SECRET: $GITHUB_SECRET
    restart: always

  sidekiq:
    <<: *rails
    command: bundle exec sidekiq
    ports: []

volumes:
  db:
  redis:
  config:
  storage:
