name: Run tests

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'
    tags:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      mariadb:
        image: mariadb
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: 1
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=5s --health-timeout=2s --health-retries=3
      redis:
        image: redis:alpine
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0

      - name: Use Node.js 15.x
        uses: actions/setup-node@v2
        with:
          node-version: 15.x

      - name: Install dependencies
        run: |
          bundle install
          npm install -g yarn
          yarn

      - name: Setup database
        run: |
          cp config/database.yml.mysql config/database.yml
          mysql -u root -h 127.0.0.1 -e 'create database imgshr_test;'

      - name: Run tests
        env:
          RAILS_ENV: test
          TZ: Europe/Berlin
        run: |
          bundle exec rails db:migrate
          bundle exec ./bin/webpack
          bundle exec rails test
          yarn lint
